spring.application.name=fieldops

spring.datasource.url=jdbc:mysql://localhost:3306/servicio_tecnico
spring.datasource.username=root
spring.datasource.password=LasAvesVuelan

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=fieldops-auth-secret-key-2026-change-me-32bytes
jwt.expiration-ms=86400000